/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package friendadder;

import javax.swing.JTextField;

/**
 *
 * @author Sam
 */
public class AppearancePanel extends javax.swing.JPanel {

    /**
     * Creates new form AppearancePanel
     */
    public AppearancePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        hairLength = new javax.swing.JTextField();
        hairColor = new javax.swing.JTextField();
        eyeColor = new javax.swing.JTextField();
        wearsGlasses = new javax.swing.JTextField();
        wearsEarrings = new javax.swing.JTextField();
        dressUpStyle = new javax.swing.JTextField();
        shoeType = new javax.swing.JTextField();
        height = new javax.swing.JTextField();
        skinTone = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel1.setText("Hair Length");

        jLabel2.setText("Hair Color");

        jLabel3.setText("Eye Color");

        jLabel4.setText("Wears Glasses");

        jLabel5.setText("Wears Earrings");

        jLabel6.setText("Dress-up Style");

        jLabel7.setText("Shoe Type");

        jLabel8.setText("Height");

        jLabel9.setText("Skin Tone");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hairColor)
                    .addComponent(hairLength)
                    .addComponent(eyeColor)
                    .addComponent(dressUpStyle)
                    .addComponent(shoeType)
                    .addComponent(height)
                    .addComponent(skinTone, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(wearsEarrings, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(wearsGlasses))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(hairLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hairColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eyeColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wearsGlasses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wearsEarrings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dressUpStyle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shoeType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(height, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(skinTone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(154, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    //Getters and setters for data fields
    
    public String getHairLength(){
        return this.hairLength.getText();
    }
    public void setHairLength(String newHairLength){
        this.hairLength.setText(newHairLength);
    }
    public String getHairColor(){
        return this.hairColor.getText();
    }
    public void setHairColor(String newHairColor){
        this.hairColor.setText(newHairColor);
    }
    public String getEyeColor(){
        return this.eyeColor.getText();
    }
    public void setEyeColor(String newEyeColor){
        this.eyeColor.setText(newEyeColor);
    }
    public Boolean getWearsGlasses(){
        if(this.wearsGlasses.getText().equals("Yes")||this.wearsGlasses.getText().equals("yes"))
            return true;
        else
            return false;
    }
    public void setWearsGlasses(boolean newWearsGlasses){
        if(newWearsGlasses==true)
            wearsGlasses.setText("Yes");
        else
            wearsGlasses.setText("No");
    }
    public boolean getWearsEarrings(){
        if(this.wearsEarrings.getText().equals("Yes")||this.wearsEarrings.getText().equals("yes"))
            return true;
        else
            return false;
    }
    public void setWearsEarrings(boolean newWearsEarrings){
        if(newWearsEarrings==true)
            wearsEarrings.setText("Yes");
        else
            wearsEarrings.setText("No");
    }
    public String getDressUpStyle(){
        return this.dressUpStyle.getText();
    }
    public void setDressUpStyle(String newDressUpStyle){
        this.dressUpStyle.setText(newDressUpStyle);
    }
    public String getShoeType(){
        return this.shoeType.getText();
    }
    public void setShoeType(String newShoeType){
        this.shoeType.setText(newShoeType);
    }
    public String getFHeight(){
        return this.height.getText();
    }
    public void setFHeight(String newHeight){
        this.height.setText(newHeight);
    }
    public String getSkinTone(){
        return this.skinTone.getText();
    }
    public void setSkinTone(String newSkinTone){
        this.skinTone.setText(newSkinTone);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dressUpStyle;
    private javax.swing.JTextField eyeColor;
    private javax.swing.JTextField hairColor;
    private javax.swing.JTextField hairLength;
    private javax.swing.JTextField height;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField shoeType;
    private javax.swing.JTextField skinTone;
    private javax.swing.JTextField wearsEarrings;
    private javax.swing.JTextField wearsGlasses;
    // End of variables declaration//GEN-END:variables
}
