/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package friendadder;

import javax.swing.JOptionPane;

/**
 *
 * @author Sam
 */
public class BasicInfoPanel extends javax.swing.JPanel {

    /**
     * Creates new form BasicInfo
     */
    public BasicInfoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        gender = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        birthDay = new javax.swing.JTextField();
        connection = new javax.swing.JTextField();
        relationshipStatus = new javax.swing.JTextField();
        getAlong = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        birthMonth = new javax.swing.JTextField();
        birthYear = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel1.setText("Name");

        name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nameMousePressed(evt);
            }
        });

        jLabel2.setText("Gender");

        jLabel3.setText("Age");

        jLabel4.setText("Birth Day");

        jLabel5.setText("Connection");

        jLabel6.setText("Relationship Status");

        jLabel7.setText("Friendship Strength");

        jLabel8.setText("Birth Month");

        jLabel9.setText("Birth Year");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(relationshipStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                    .addComponent(connection)
                    .addComponent(name)
                    .addComponent(gender)
                    .addComponent(getAlong, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(age, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(birthDay, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(birthMonth, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(birthYear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(birthDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(birthMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(birthYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(connection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(relationshipStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getAlong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(154, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameMousePressed

    }//GEN-LAST:event_nameMousePressed
    
    //Getters and setters for data fields
    
    public String getFName(){
        return this.name.getText();
    }
    public void setFName(String newName){
        this.name.setText(newName);
    }
    public String getGender(){
        return this.gender.getText();
    }
    public void setGender(String newGender){
        this.gender.setText(newGender);
    }
    public int getAge(){
        return Integer.parseInt(age.getText());
    }
    public void setAge(int newAge){
        age.setText(String.valueOf(newAge));
    }
    public int getBirthday(){
        return Integer.parseInt(birthDay.getText());
    }
    public void setBirthday(int newBirthday){
        birthDay.setText(String.valueOf(newBirthday));
    }
    public int getBirthMonth(){
        switch (birthMonth.getText()) {
            case "January":
                return 1;
            case "February":
                return 2;
            case "March":
                return 3;
            case "April":
                return 4;
            case "May":
                return 5;
            case "june":
                return 6;
            case "July":
                return 7;
            case "August":
                return 8;
            case "September":
                return 9;
            case "October":
                return 10;
            case "November":
                return 11;
            case "December":
                return 12;
            default:
                return 1;
        }
    }
    public void setBirthMonth(int newBirthMonth){
        if(newBirthMonth==0||newBirthMonth==1)
            birthMonth.setText("January");
        else if(newBirthMonth==2)
            birthMonth.setText("February");
        else if(newBirthMonth==3)
            birthMonth.setText("March");
        else if(newBirthMonth==4)
            birthMonth.setText("April");
        else if(newBirthMonth==5)
            birthMonth.setText("May");
        else if(newBirthMonth==6)
            birthMonth.setText("June");
        else if(newBirthMonth==7)
            birthMonth.setText("July");
        else if(newBirthMonth==8)
            birthMonth.setText("August");
        else if(newBirthMonth==9)
            birthMonth.setText("September");
        else if(newBirthMonth==10)
            birthMonth.setText("October");
        else if(newBirthMonth==11)
            birthMonth.setText("November");
        else
            birthMonth.setText("December");
    }
    public int getBirthYear(){
        return Integer.parseInt(birthYear.getText());
    }
    public void setBirthYear(int newBirthYear){
        birthYear.setText(String.valueOf(newBirthYear));
    }
    public String getConnection(){
        return connection.getText();
    }
    public void setConnection(String newConnection){
        connection.setText(newConnection);
    }
    public String getRelationshipStatus(){
        return relationshipStatus.getText();
    }
    public void setRelationshipStatus(String newRelationshipStatus){
        relationshipStatus.setText(newRelationshipStatus);
    }
    public String getGetAlong(){
        return getAlong.getText();
    }
    public void setGetAlong(String newGetAlong){
        getAlong.setText(newGetAlong);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.JTextField birthDay;
    private javax.swing.JTextField birthMonth;
    private javax.swing.JTextField birthYear;
    private javax.swing.JTextField connection;
    private javax.swing.JTextField gender;
    private javax.swing.JTextField getAlong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField name;
    private javax.swing.JTextField relationshipStatus;
    // End of variables declaration//GEN-END:variables
}
