/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package friendadder;

/**
 *
 * @author Sam
 */
public class FavoritesPanel extends javax.swing.JPanel {

    /**
     * Creates new form FavoritesPanel
     */
    public FavoritesPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        favMusic = new javax.swing.JTextField();
        favRestaurants = new javax.swing.JTextField();
        favVideoGames = new javax.swing.JTextField();
        favNonVideoGames = new javax.swing.JTextField();
        favMovies = new javax.swing.JTextField();
        favShows = new javax.swing.JTextField();
        favBooks = new javax.swing.JTextField();
        favHobbies = new javax.swing.JTextField();
        favSports = new javax.swing.JTextField();
        favPeople = new javax.swing.JTextField();
        favFoods = new javax.swing.JTextField();
        favClothesBrands = new javax.swing.JTextField();
        favAnimals = new javax.swing.JTextField();
        favTraditions = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        jLabel1.setText("Music");

        jLabel2.setText("Restaurants");

        jLabel3.setText("Video Games");

        jLabel4.setText("Non Video Games");

        jLabel5.setText("Movies");

        jLabel6.setText("Shows");

        jLabel7.setText("Books");

        jLabel8.setText("Hobbies");

        jLabel9.setText("Sports");

        jLabel10.setText("People");

        jLabel11.setText("Foods");

        jLabel12.setText("Clothes Brands");

        jLabel13.setText("Animals");

        jLabel14.setText("Traditions");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(favMusic, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(favTraditions, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                        .addComponent(favAnimals, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(favClothesBrands, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(favFoods, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(favPeople, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(favSports, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(favHobbies, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(favBooks, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(favShows, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(favMovies, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(favRestaurants, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(favVideoGames, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(favNonVideoGames, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(favMusic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(favRestaurants, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(favVideoGames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(favNonVideoGames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(favMovies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(favShows, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(favBooks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(favHobbies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(favSports, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(favPeople, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(favFoods, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(favClothesBrands, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(favAnimals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(favTraditions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    //Getters and setters for data fields
    
    public String getFavMusic(){
        return this.favMusic.getText();
    }
    public void setFavMusic(String newFavMusic){
        this.favMusic.setText(newFavMusic);
    }
    public String getFavRestaurants(){
        return this.favRestaurants.getText();
    }
    public void setFavRestaurants(String newFavRestaurants){
        this.favRestaurants.setText(newFavRestaurants);
    }
    public String getFavVideoGames(){
        return this.favVideoGames.getText();
    }
    public void setFavVideoGames(String newFavVideoGames){
        this.favVideoGames.setText(newFavVideoGames);
    }
    public String getFavNonVideoGames(){
        return this.favNonVideoGames.getText();
    }
    public void setFavNonVideoGames(String newFavNonVideoGames){
        this.favNonVideoGames.setText(newFavNonVideoGames);
    }
    public String getFavMovies(){
        return this.favMovies.getText();
    }
    public void setFavMovies(String newFavMovies){
        this.favMovies.setText(newFavMovies);
    }
    public String getFavShows(){
        return this.favShows.getText();
    }
    public void setFavShows(String newFavShows){
        this.favShows.setText(newFavShows);
    }
    public String getFavBooks(){
        return this.favBooks.getText();
    }
    public void setFavBooks(String newFavBooks){
        this.favBooks.setText(newFavBooks);
    }
    public String getFavHobbies(){
        return this.favHobbies.getText();
    }
    public void setFavHobbies(String newFavHobbies){
        this.favHobbies.setText(newFavHobbies);
    }
    public String getFavSports(){
        return this.favSports.getText();
    }
    public void setFavSports(String newFavSports){
        this.favSports.setText(newFavSports);
    }
    public String getFavPeople(){
        return this.favPeople.getText();
    }
    public void setFavPeople(String newFavPeople){
        this.favPeople.setText(newFavPeople);
    }
    public String getFavFoods(){
        return this.favFoods.getText();
    }
    public void setFavFoods(String newFavFoods){
        this.favFoods.setText(newFavFoods);
    }
    public String getFavClothesBrand(){
        return this.favClothesBrands.getText();
    }
    public void setFavClothesBrand(String newFavClothesBrand){
        this.favClothesBrands.setText(newFavClothesBrand);
    }
    public String getFavAnimals(){
        return this.favAnimals.getText();
    }
    public void setFavAnimals(String newFavAnimal){
        this.favAnimals.setText(newFavAnimal);
    }
    public String getFavTraditions(){
        return this.favTraditions.getText();
    }
    public void setFavTraditions(String newFavTradition){
        this.favTraditions.setText(newFavTradition);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField favAnimals;
    private javax.swing.JTextField favBooks;
    private javax.swing.JTextField favClothesBrands;
    private javax.swing.JTextField favFoods;
    private javax.swing.JTextField favHobbies;
    private javax.swing.JTextField favMovies;
    private javax.swing.JTextField favMusic;
    private javax.swing.JTextField favNonVideoGames;
    private javax.swing.JTextField favPeople;
    private javax.swing.JTextField favRestaurants;
    private javax.swing.JTextField favShows;
    private javax.swing.JTextField favSports;
    private javax.swing.JTextField favTraditions;
    private javax.swing.JTextField favVideoGames;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
