/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package friendadder;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import com.sun.security.auth.module.NTSystem;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;

/**
 *
 * @author Sam
 */
public class FirstTimeSetup extends javax.swing.JFrame {
    private String os; //Operating System.
    private String username; //name of user
    private String programPath; //Path of program
    /**
     * Creates new form FirstTimeSetup
     */
    public FirstTimeSetup() throws IOException {
        initComponents();
        this.os=System.getProperty("os.name");
        this.username=System.getProperty("user.name");
        System.out.println(os);
        System.out.println(username);
        System.out.println(System.getProperty("user.dir"));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Make Folder");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        jLabel1.setText("The following directory will be created: \"C:/Users/"+System.getProperty("user.name")+"/Documents/Friend Adder Files\"");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jButton1)))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jButton1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        
        File mainFolder=new File("C:\\Users\\"+this.username+"\\Documents\\FriendshipAdder Files");
        mainFolder.mkdir();
        File friendFolder=new File(FirstTimeSetup.getFriendsPath());
        friendFolder.mkdir();
        File picFolder=new File(FirstTimeSetup.getPicturesPath());
        picFolder.mkdir();
        File picture=new File("blank.png");
        BufferedImage image;
        try {
            image = ImageIO.read(picture);
            File file=new File(FirstTimeSetup.getPicturesPath()+"blank.png");
            ImageIO.write(image, "png", file);
        } catch (IOException ex) {
            Logger.getLogger(FirstTimeSetup.class.getName()).log(Level.SEVERE, null, ex);
        }
        TheGUI g=new TheGUI();
        g.setTitle("FriendshipAdder");
        g.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1MousePressed
    
    //returns program directory
    public static String getProgramPath(){
        return "C:\\Users\\"+System.getProperty("user.name")+"\\Documents\\FriendshipAdder Files\\";
    }
    
    //returns friend directory
    public static String getFriendsPath(){
        return FirstTimeSetup.getProgramPath()+"friends\\";
    }
    
    //returns picture directory
    public static String getPicturesPath(){
        return FirstTimeSetup.getProgramPath()+"pictures\\";
    }
    
    //returns operating system name
    public String getOS(){
        return this.os;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstTimeSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstTimeSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstTimeSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstTimeSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            //Runs first time setup if there is no program directory. Otherwise goes to the main GUI.
            public void run() {
                try {
                    File test=new File("C:\\Users\\"+System.getProperty("user.name")+"\\Documents\\FriendshipAdder Files");
                    if(!test.exists())
                        new FirstTimeSetup().setVisible(true);
                    else
                        new TheGUI().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(FirstTimeSetup.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
