/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package friendadder;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Sam
 */
public class Selector extends javax.swing.JFrame{
    private TheGUI gui;
    /**
     * Creates new form Selector
     */
    public Selector(TheGUI g) {
        initComponents();
        this.gui=g;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jList1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);
        this.jList1.setModel(new javax.swing.AbstractListModel() {
            File folder=new File(FirstTimeSetup.getFriendsPath());
            File[] files=folder.listFiles();
            String[] strings = new String[files.length];
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MousePressed
        //User selects friend
        String selected=(String)(this.jList1.getSelectedValue());
        String path=FirstTimeSetup.getProgramPath();
        File selectedFile=new File(FirstTimeSetup.getFriendsPath()+selected+".txt");
        try {
            gui.setFileSelected(selectedFile);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Selector.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Selector.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_jList1MousePressed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        //Brings up friend list
        String path=FirstTimeSetup.getFriendsPath();
        File folder=new File(path);
        File[] files=folder.listFiles();
        System.out.println("Searching...");
        final String[] strings=new String[files.length];
        for(int q=0; q<files.length; q++){
                strings[q]=files[q].getName();
                strings[q]=strings[q].substring(0, strings[q].length()-4);
        }
            this.jList1.setModel(new javax.swing.AbstractListModel() {
       
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });      
        
        
    }//GEN-LAST:event_formComponentShown

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}